// nuxt-project/components/domain/ReportAnalysis.vue
<template>
  <div class="space-y-6">
    <div>
      <h2 class="text-2xl font-bold">리포트 분석</h2>
      <p class="text-slate-600 mt-1">증권사 애널리스트 리포트 및 목표가 분석</p>
    </div>

    <!-- Tabs -->
    <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-4">
      <div class="grid grid-cols-4 lg:grid-cols-8 gap-2">
        <button
          v-for="tab in tabs"
          :key="tab"
          @click="activeTab = tab"
          :class="[
            'text-xs py-2 rounded-md transition-colors',
            activeTab === tab
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white text-slate-700 border border-slate-200 hover:bg-slate-50'
          ]"
        >
          {{ tab }}
        </button>
      </div>
    </div>

    <!-- Table -->
    <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
      <div class="flex justify-end mb-4">
        <span class="text-sm text-slate-500">업데이트 01/22 09:25</span>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="border-b-2 border-slate-300">
              <th class="text-center py-3 px-4 font-semibold text-slate-700">날짜</th>
              <th class="text-left py-3 px-4 font-semibold text-slate-700">종목명</th>
              <th class="text-right py-3 px-4 font-semibold text-slate-700">등락률</th>
              
              <template v-if="activeTab === '기관관심리포트'">
                <th class="text-right py-3 px-4 font-semibold text-slate-700">기관누적순매매금액</th>
              </template>
              <template v-else-if="activeTab === '외국인관심리포트'">
                <th class="text-right py-3 px-4 font-semibold text-slate-700">외국인누적순매매금액</th>
              </template>
              <template v-else-if="activeTab === '연기금관심리포트'">
                <th class="text-right py-3 px-4 font-semibold text-slate-700">연기금누적순매매금액</th>
              </template>
              <template v-else-if="activeTab === '증권사관심종목'">
                <th class="text-center py-3 px-4 font-semibold text-slate-700">리포트수량</th>
                <th class="text-right py-3 px-4 font-semibold text-slate-700">최고목표가</th>
                <th class="text-right py-3 px-4 font-semibold text-slate-700">최저목표가</th>
              </template>
              <template v-else-if="activeTab === '목표가높음'">
                <th class="text-right py-3 px-4 font-semibold text-slate-700">목표가</th>
                <th class="text-center py-3 px-4 font-semibold text-slate-700">주가대비</th>
              </template>
              <template v-else>
                <th class="text-right py-3 px-4 font-semibold text-slate-700">목표가</th>
                <th class="text-center py-3 px-4 font-semibold text-slate-700">투자의견</th>
              </template>

              <th class="text-left py-3 px-4 font-semibold text-slate-700">
                {{ activeTab === '증권사관심종목' ? '최신리포트' : '제목' }}
              </th>
              <th v-if="activeTab !== '증권사관심종목'" class="text-center py-3 px-4 font-semibold text-slate-700">증권사</th>
            </tr>
          </thead>
          <tbody>
            <tr 
              v-for="(report, idx) in currentData" 
              :key="idx" 
              class="border-b border-slate-200 hover:bg-slate-50 transition-colors"
            >
              <td class="py-3 px-4 text-center text-slate-600">{{ report.date }}</td>
              <td class="py-3 px-4 font-medium text-blue-600 cursor-pointer hover:underline">
                <div class="flex items-center gap-2">
                  <div :class="['w-6 h-6 rounded-full flex items-center justify-center text-white font-bold text-xs flex-shrink-0', getStockColor(report.stockName)]">
                    {{ report.stockName.charAt(0) }}
                  </div>
                  <span>{{ report.stockName }}</span>
                </div>
              </td>
              <td :class="['py-3 px-4 text-right font-semibold', report.changeRate > 0 ? 'text-red-600' : report.changeRate < 0 ? 'text-blue-600' : 'text-slate-600']">
                 {{ report.changeRate > 0 ? '+' : '' }}{{ report.changeRate }}%
              </td>

              <!-- Dynamic Columns -->
              <template v-if="activeTab === '기관관심리포트'">
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ report.institutionalAmount }}</td>
              </template>
              <template v-else-if="activeTab === '외국인관심리포트'">
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ report.foreignAmount }}</td>
              </template>
              <template v-else-if="activeTab === '연기금관심리포트'">
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ report.pensionAmount }}</td>
              </template>
              <template v-else-if="activeTab === '증권사관심종목'">
                 <td class="py-3 px-4 text-center font-semibold text-slate-900">{{ report.reportCount }}</td>
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ formatPrice(report.highestTargetPrice) }}</td>
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ formatPrice(report.lowestTargetPrice) }}</td>
              </template>
              <template v-else-if="activeTab === '목표가높음'">
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ formatPrice(report.targetPrice) }}</td>
                 <td class="py-3 px-4 text-center font-semibold text-slate-900">{{ report.targetVsPrice }}</td>
              </template>
              <template v-else>
                 <td class="py-3 px-4 text-right font-semibold text-slate-900">{{ formatPrice(report.targetPrice) }}</td>
                 <td class="py-3 px-4 text-center">
                    <span :class="['inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent', getRatingColor(report.rating)]">
                        {{ report.rating }}
                    </span>
                 </td>
              </template>

              <td 
                class="py-3 px-4 text-slate-700 max-w-md truncate cursor-pointer hover:text-blue-600 hover:underline"
                @click="selectedReport = report"
              >
                {{ report.title }}
              </td>
              <td v-if="activeTab !== '증권사관심종목'" class="py-3 px-4 text-center text-slate-600">
                {{ report.firm }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

       <!-- Pagination & Legend -->
      <div class="flex justify-between items-center mt-6 pt-4 border-t border-slate-200">
        <div class="text-sm text-slate-600">
            {{ getTabDescription(activeTab) }}
        </div>
        <div class="flex items-center gap-2">
            <button class="px-3 py-1 border border-slate-300 rounded hover:bg-slate-100 disabled:opacity-50 disabled:cursor-not-allowed">‹</button>
            <button class="px-3 py-1 bg-blue-600 text-white rounded">1</button>
            <button class="px-3 py-1 border border-slate-300 rounded hover:bg-slate-100">2</button>
            <button class="px-3 py-1 border border-slate-300 rounded hover:bg-slate-100">›</button>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div v-if="selectedReport" class="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6" role="dialog" aria-modal="true">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true" @click="selectedReport = null"></div>
        
        <div class="bg-white rounded-lg shadow-xl transform transition-all sm:max-w-lg sm:w-full max-h-[80vh] flex flex-col pointer-events-auto border border-slate-200">
            <div class="p-6 overflow-y-auto">
                <div class="flex justify-between items-start mb-4">
                     <h3 class="text-lg font-bold pr-8">
                        [{{ selectedReport.stockName }}]<br />
                        {{ selectedReport.title }}
                     </h3>
                     <button @click="selectedReport = null" type="button" class="text-slate-400 hover:text-slate-600">
                        <x class="w-6 h-6" />
                     </button>
                </div>

                <div class="text-sm text-slate-500 mb-6">
                    {{ selectedReport.firm }} | {{ selectedReport.date }}
                </div>

                <div class="space-y-3 mb-6">
                    <div>
                        <span class="text-sm text-slate-600">목표가 : </span>
                        <span class="font-semibold">{{ formatPrice(selectedReport.targetPrice) }} 원</span>
                    </div>
                     <div>
                        <span class="text-sm text-slate-600">투자의견 : </span>
                        <span class="font-semibold">{{ selectedReport.rating }}</span>
                    </div>
                </div>

                 <div class="text-sm text-slate-700 leading-relaxed">
                    {{ selectedReport.content || '상세 내용이 제공되지 않습니다.' }}
                </div>
            </div>
        </div>
    </div>
  </div>
</template>

<script>
import { X } from 'lucide-vue';

const mockReports = {
  '신규리포트': [
    { 
      date: '01/22', stockName: '두산에스나', currentPrice: 52600, changeRate: 1.94, targetPrice: 69000, 
      title: '비메모리 턴어라운드와 직관적인 동행', firm: '교보증권', rating: 'BUY(신규)', upside: 31.5,
      content: '국내 대표 시스템반도체 디자인하우스. DSP 전환의 성과가 보여줄 원년...'
    },
    // ... Add more mock data as needed
  ],
  // ... Add structure for other tabs to avoid errors, empty initially
  '목표가상향': [],
  '목표가하향': [],
  '기관관심리포트': [],
  '외국인관심리포트': [],
  '연기금관심리포트': [],
  '증권사관심종목': [],
  '목표가높음': []
};

export default {
    name: 'ReportAnalysis',
    components: {
        X
    },
    data() {
        return {
            activeTab: '신규리포트',
            selectedReport: null,
            tabs: [
                '신규리포트', '목표가상향', '목표가하향', '기관관심리포트', 
                '외국인관심리포트', '연기금관심리포트', '증권사관심종목', '목표가높음'
            ],
            reportsData: mockReports
        }
    },
    computed: {
        currentData() {
            return this.reportsData[this.activeTab] || [];
        }
    },
    methods: {
        formatPrice(price) {
            return price ? price.toLocaleString() : '-';
        },
        getStockColor(stockName) {
            const colors = [
                'bg-blue-500', 'bg-indigo-500', 'bg-purple-500', 'bg-pink-500',
                'bg-red-500', 'bg-orange-500', 'bg-amber-500', 'bg-yellow-500',
                'bg-lime-500', 'bg-green-500', 'bg-emerald-500', 'bg-teal-500',
                'bg-cyan-500', 'bg-sky-500', 'bg-violet-500', 'bg-fuchsia-500'
            ];
            const index = stockName.charCodeAt(0) % colors.length;
            return colors[index];
        },
        getRatingColor(rating) {
            if (!rating) return 'bg-gray-100 text-gray-700 border-gray-300';
            const r = rating.toLowerCase();
            if (r.includes('buy')) return 'bg-green-100 text-green-700 border-green-300';
            if (r.includes('hold')) return 'bg-yellow-100 text-yellow-700 border-yellow-300';
            if (r.includes('sell')) return 'bg-red-100 text-red-700 border-red-300';
            return 'bg-gray-100 text-gray-700 border-gray-300';
        },
        getTabDescription(tab) {
             const descriptions = {
                '신규리포트': "신규리포트는 증권사에서 '신규매수'의견을 제시한 리포트 입니다.",
                '목표가상향': "해당 증권사에서 최근 3개월이내에 발표한 리포트 중, 직전 목표가 대비 목표가가 상향된 종목입니다.",
                '목표가하향': "해당 증권사에서 최근 3개월이내에 발표한 리포트 중, 직전 목표가 대비 목표가가 하향된 종목입니다.",
                '기관관심리포트': "리포트 발표 당일 기관의 순매수량이 큰 종목입니다.",
                '외국인관심리포트': "리포트 발표 당일 외국인의 순매수량이 큰 종목입니다.",
                '연기금관심리포트': "리포트 발표 당일 연기금의 순매수량이 큰 종목입니다.",
                '증권사관심종목': "오늘 증권사의 리포트가 많이 발생한 종목입니다.",
                '목표가높음': "오늘 발표한 리포트 중, 목표가와 현재가의 괴리율이 큰 종목입니다."
             };
             return descriptions[tab] || "";
        }
    }
}
</script>

// src/app/components/investment/report-analysis.tsx
import { Card, CardContent, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Badge } from '@/app/components/ui/badge';
import { Button } from '@/app/components/ui/button';
import { FileBarChart, TrendingUp, TrendingDown, Building2, X, Circle, Calendar, ChevronLeft, ChevronRight } from "lucide-react";
import { useState } from 'react';
import { cn } from "@/app/components/ui/utils";

type TabType = '신규리포트' | '목표가상향' | '목표가하향' | '기관관심리포트' | '외국인관심리포트' | '연기금관심리포트' | '증권사관심종목' | '목표가높음';

interface ReportData {
  date: string;
  stockName: string;
  currentPrice: number;
  changeRate: number;
  targetPrice: number;
  title: string;
  firm: string;
  rating: string;
  upside: number;
  content?: string;
  institutionalAmount?: string;
  foreignAmount?: string;
  pensionAmount?: string;
  reportCount?: number;
  highestTargetPrice?: number;
  lowestTargetPrice?: number;
  targetVsPrice?: string;
}

const mockReports: Record<TabType, ReportData[]> = {
  신규리포트: [
    {
      date: "01/22",
      stockName: "두산에스나",
      currentPrice: 52600,
      changeRate: 1.94,
      targetPrice: 69000,
      title: "비메모리 턴어라운드와 직관적인 동행",
      firm: "교보증권",
      rating: "BUY(신규)",
      upside: 31.5,
      content: "국내 대표 시스템반도체 디자인하우스. DSP 전환의 성과가 보여줄 원년. 동사는 약 20년간 DSP를 사용한 통신 칩을 점유해왔다."
    },
    {
      date: "01/22",
      stockName: "에이디테크놀로지",
      currentPrice: 34750,
      changeRate: 1.46,
      targetPrice: 45000,
      title: "DSP 전환의 결실을 맺을 엔넬",
      firm: "교보증권",
      rating: "BUY(신규)",
      upside: 29.5,
      content: "국내 대표 시스템반도체 디자인하우스로서 비메모리 반도체 턴어라운드의 수혜가 기대됩니다."
    },
    { date: "01/22", stockName: "네패스", currentPrice: 15380, changeRate: -1.41, targetPrice: 20000, title: "지정학적 불확실성이 가져온 혼재", firm: "교보증권", rating: "HOLD", upside: 30.1 },
    { date: "01/21", stockName: "아모센스", currentPrice: 10090, changeRate: 8.15, targetPrice: 16000, title: "블랭에서기 수혜 본격화, 동반된 리레이팅", firm: "DS투자증권", rating: "BUY", upside: 58.5 },
    { date: "01/21", stockName: "유비쿼스", currentPrice: 11930, changeRate: 29.96, targetPrice: 22000, title: "아직 달글달지 않은 피지컬 AI 수혜주", firm: "하나증권", rating: "BUY", upside: 84.4 },
    { date: "01/20", stockName: "에스티", currentPrice: 17530, changeRate: 2.57, targetPrice: 28000, title: "HBM과 HPA가 이끄어낼 가파른 실적 기울기", firm: "리딩투자증권", rating: "BUY", upside: 60.3 },
    { date: "01/20", stockName: "한솔케미칼", currentPrice: 261000, changeRate: 6.31, targetPrice: 325000, title: "반도체 업사이클과 2차전지 소재의 부활", firm: "NH투자증권", rating: "BUY", upside: 24.5 },
    { date: "01/20", stockName: "삼성전자", currentPrice: 74500, changeRate: 2.05, targetPrice: 85000, title: "AI 반도체 수요 증가로 목표가 상향", firm: "KB증권", rating: "BUY", upside: 14.1 }
  ],
  목표가상향: [
    { date: "01/22", stockName: "삼성전자", currentPrice: 74500, changeRate: 2.05, targetPrice: 85000, title: "AI 반도체 수요 증가로 목표가 상향", firm: "KB증권", rating: "BUY", upside: 14.1 },
    { date: "01/22", stockName: "SK하이닉스", currentPrice: 142000, changeRate: 3.27, targetPrice: 165000, title: "HBM3E 수주 확대, 목표가 상향", firm: "신한투자증권", rating: "BUY", upside: 16.2 }
  ],
  목표가하향: [],
  기관관심리포트: [],
  외국인관심리포트: [],
  연기금관심리포트: [],
  증권사관심종목: [],
  목표가높음: []
};

const getRatingStyle = (rating: string) => {
  if (rating.includes("BUY")) return "bg-blue-50 text-blue-600 border-blue-100";
  if (rating.includes("HOLD")) return "bg-slate-50 text-slate-600 border-slate-200";
  if (rating.includes("SELL")) return "bg-red-50 text-red-600 border-red-100";
  return "bg-slate-50 text-slate-600 border-slate-200";
};

const getStockInitialColor = (name: string) => {
  const colors = ["bg-blue-500", "bg-indigo-500", "bg-purple-500", "bg-pink-500", "bg-red-500", "bg-orange-500"];
  return colors[name.charCodeAt(0) % colors.length];
};

export function ReportAnalysis() {
  const [activeTab, setActiveTab] = useState<TabType>('신규리포트');
  const [selectedReport, setSelectedReport] = useState<ReportData | null>(null);

  const data = mockReports[activeTab] || [];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">리포트 분석</h2>
          <p className="text-slate-500 mt-1">증권사 애널리스트 리포트 및 목표가 변동 현황입니다.</p>
        </div>
        <div className="flex items-center gap-2 text-xs font-semibold text-slate-400 bg-slate-100 px-3 py-1.5 rounded-full">
          <Calendar className="w-3.5 h-3.5" />
          마지막 업데이트: 2024.01.22 09:25
        </div>
      </div>

      <Card className="border-none shadow-sm bg-slate-50 overflow-hidden">
        <CardContent className="p-1">
          <div className="flex flex-wrap gap-1">
            {(Object.keys(mockReports) as TabType[]).map((tab) => (
              <button key={tab} onClick={() => setActiveTab(tab)} className={cn("px-4 py-2.5 text-xs font-bold rounded-lg transition-all", activeTab === tab ? "bg-white text-blue-600 shadow-sm" : "text-slate-500 hover:bg-white/50 hover:text-slate-700")}>
                {tab}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card className="border-slate-200 shadow-sm overflow-hidden">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/50 border-b border-slate-100">
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider text-center w-20">날짜</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider">종목명</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider text-right">등락률</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider text-right">목표가</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider text-center">투자의견</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider">리포트 제목</th>
                  <th className="py-4 px-6 text-[11px] font-bold text-slate-400 uppercase tracking-wider text-center">증권사</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {data.length > 0 ? (
                  data.map((report, idx) => (
                    <tr key={idx} className="hover:bg-blue-50/30 transition-colors group">
                      <td className="py-4 px-6 text-sm text-slate-500 text-center font-medium">{report.date}</td>
                      <td className="py-4 px-6">
                        <div className="flex items-center gap-3">
                          <div className={cn("w-8 h-8 rounded-lg flex items-center justify-center text-white text-[10px] font-bold shadow-sm", getStockInitialColor(report.stockName))}>{report.stockName.substring(0, 1)}</div>
                          <span className="text-sm font-bold text-slate-800 group-hover:text-blue-600 cursor-pointer">{report.stockName}</span>
                        </div>
                      </td>
                      <td className={cn("py-4 px-6 text-sm text-right font-bold", report.changeRate > 0 ? "text-red-500" : report.changeRate < 0 ? "text-blue-500" : "text-slate-500")}>
                        {report.changeRate > 0 ? "+" : ""}
                        {report.changeRate}%
                      </td>
                      <td className="py-4 px-6 text-sm text-right font-bold text-slate-900">{report.targetPrice.toLocaleString()}</td>
                      <td className="py-4 px-6 text-center">
                        <Badge variant="outline" className={cn("px-2.5 py-1 text-[10px] font-bold rounded-md border", getRatingStyle(report.rating))}>
                          {report.rating}
                        </Badge>
                      </td>
                      <td className="py-4 px-6 text-sm text-slate-700 font-medium max-w-md truncate cursor-pointer hover:text-blue-600 hover:underline" onClick={() => setSelectedReport(report)}>
                        {report.title}
                      </td>
                      <td className="py-4 px-6 text-sm text-slate-500 text-center font-semibold">{report.firm}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={7} className="py-20 text-center text-slate-400 font-medium">
                      데이터가 존재하지 않습니다.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="flex items-center justify-between p-6 border-t border-slate-100 bg-slate-50/30">
            <div className="text-xs font-semibold text-slate-500">{activeTab === "신규리포트" ? "※ 신규리포트는 증권사에서 신규 매수 의견을 제시한 리포트입니다." : "※ 가이드 정보를 확인해 주세요."}</div>
            <div className="flex items-center gap-1">
              <Button variant="ghost" size="icon" className="w-8 h-8 rounded-lg border border-slate-200">
                <ChevronLeft className="w-4 h-4" />
              </Button>
              <div className="flex gap-1 px-2">
                <Button variant="ghost" size="sm" className="w-8 h-8 p-0 rounded-lg bg-blue-600 text-white font-bold hover:bg-blue-700">
                  1
                </Button>
                <Button variant="ghost" size="sm" className="w-8 h-8 p-0 rounded-lg text-slate-500 font-bold hover:bg-slate-100">
                  2
                </Button>
                <Button variant="ghost" size="sm" className="w-8 h-8 p-0 rounded-lg text-slate-500 font-bold hover:bg-slate-100">
                  3
                </Button>
              </div>
              <Button variant="ghost" size="icon" className="w-8 h-8 rounded-lg border border-slate-200">
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* 리포트 상세 팝업 */}
      {selectedReport && (
        <div className="fixed inset-0 flex items-center justify-center z-50 p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
          <Card className="max-w-xl w-full max-h-[85vh] overflow-hidden flex flex-col shadow-2xl border-none animate-in zoom-in-95 duration-200">
            <CardHeader className="border-b bg-slate-50/50 relative py-6 px-8">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <Badge className="bg-blue-600 hover:bg-blue-600">{selectedReport.stockName}</Badge>
                  <span className="text-sm font-semibold text-slate-400">
                    {selectedReport.firm} • {selectedReport.date}
                  </span>
                </div>
                <CardTitle className="text-xl font-bold text-slate-900 leading-tight pt-2">{selectedReport.title}</CardTitle>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setSelectedReport(null)} className="absolute right-4 top-4 text-slate-400 hover:text-slate-600 rounded-full">
                <X className="w-5 h-5" />
              </Button>
            </CardHeader>
            <CardContent className="flex-1 overflow-y-auto p-8 bg-white">
              <div className="grid grid-cols-2 gap-4 mb-8">
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                  <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">목표주가</p>
                  <p className="text-xl font-black text-slate-900">{selectedReport.targetPrice.toLocaleString()}원</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                  <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">투자의견</p>
                  <p className="text-xl font-black text-blue-600">{selectedReport.rating}</p>
                </div>
              </div>
              <div className="space-y-4">
                <h4 className="font-bold text-slate-800 flex items-center gap-2">
                  <div className="w-1.5 h-4 bg-blue-600 rounded-full" />
                  분석 포인트
                </h4>
                <p className="text-sm text-slate-600 leading-relaxed font-medium">{selectedReport.content || "상세 데이터 요약 정보를 불러오는 중입니다..."}</p>
              </div>
            </CardContent>
            <div className="p-6 border-t bg-slate-50 flex justify-end gap-3 px-8">
              <Button variant="outline" onClick={() => setSelectedReport(null)} className="font-bold h-11 px-6 rounded-xl border-slate-200">
                취소
              </Button>
              <Button className="font-bold h-11 px-8 rounded-xl bg-blue-600 hover:bg-blue-700 shadow-lg shadow-blue-100">전체 리포트 보기</Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
